# This file was generated by GoReleaser. DO NOT EDIT.
cask "waggle" do
  version "0.19.0"

  on_macos do
    on_intel do
      sha256 "2d1125e6394090b4c0d9a0eda6e33200326d01fa639034e4f758e2c2b82a4f49"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
    on_arm do
      sha256 "481c36ffaaea6eae0d6dc9a958ffcfd004d2ebca113c605c768cd72786a8244d"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
  end

  on_linux do
    on_intel do
      sha256 "0aa1ee32d2aeadec7fa7b1032ed52ba6f66f7befb95fde30f8edb90aac18f6c5"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
    on_arm do
      sha256 "cf1a85546bbf1e6b78d5d24bcc68ae60416bf38b06dfdd0a27f9ed3e485933a1"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_linux_arm64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
  end

  name "waggle"
  desc "Local OpenTelemetry viewer — OTLP/HTTP + OTLP/gRPC ingest into SQLite + Honeycomb-style UI"
  homepage "https://github.com/danielloader/waggle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waggle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/waggle"]
    end
  end

  # No zap stanza required

end
