# This file was generated by GoReleaser. DO NOT EDIT.
cask "waggle" do
  version "0.17.1"

  on_macos do
    on_intel do
      sha256 "c55537d6cc92fa8752d699169ea29956f12cf4787d29e1c0ed6e8dd565df7285"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
    on_arm do
      sha256 "d671af3fb6f70da234cd95c8b73376fb56b5d962d0a90a4b888bfc0a1bec23f9"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
  end

  on_linux do
    on_intel do
      sha256 "531c8ea0ad024318bf0147539fa3e43a1f1f230b7311ca31d3b9c846d5ed5636"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
    on_arm do
      sha256 "ac68d50b661e421c3465288ddafca557bfea0428f311a7598c9a6a83c84fcb10"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_linux_arm64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
  end

  name "waggle"
  desc "Local OpenTelemetry viewer — OTLP/HTTP + OTLP/gRPC ingest into SQLite + Honeycomb-style UI"
  homepage "https://github.com/danielloader/waggle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waggle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/waggle"]
    end
  end

  # No zap stanza required

end
