# This file was generated by GoReleaser. DO NOT EDIT.
cask "waggle" do
  version "0.17.2"

  on_macos do
    on_intel do
      sha256 "a2d17d5618b0bf21760862903039f2f20a084ef8acb562e57ed183bb291dfcf5"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
    on_arm do
      sha256 "2798e787c126a29db7bf583278ddca7a2f6a74e814fd6ad4f87781025cc30776"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
  end

  on_linux do
    on_intel do
      sha256 "2340b013b1c2070045c55d41ffb4698505702f11fe9cfc9433fd179360179616"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
    on_arm do
      sha256 "8f64c9fe9c284f5659ce525a8cad89f86078a56b04d082a50b4c17b8b2e11f31"
      url "https://github.com/danielloader/waggle/releases/download/v#{version}/waggle_#{version}_linux_arm64.tar.gz",
        verified: "github.com/danielloader/waggle"
    end
  end

  name "waggle"
  desc "Local OpenTelemetry viewer — OTLP/HTTP + OTLP/gRPC ingest into SQLite + Honeycomb-style UI"
  homepage "https://github.com/danielloader/waggle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waggle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/waggle"]
    end
  end

  # No zap stanza required

end
