# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flashpoint < Formula
  desc "Hot reload for Go HTTP servers with a Vite/React front end, without dropped requests"
  homepage "https://github.com/danielloader/flashpoint"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.1.0/flashpoint_0.1.0_darwin_x86_64.tar.gz"
      sha256 "b93f1a87b2e28816d461ed0896b856c74c497c2e775e14fab09ee7221d226631"

      define_method(:install) do
        bin.install "flashpoint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.1.0/flashpoint_0.1.0_darwin_arm64.tar.gz"
      sha256 "12abfed0382623d0ac5f09d298081c6bdb4622e52488ba448862fe32c3eeae3f"

      define_method(:install) do
        bin.install "flashpoint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.1.0/flashpoint_0.1.0_linux_x86_64.tar.gz"
      sha256 "1a003e8c5a3e491625f0e59c8554edb3da9a53d399fa11ae5128ad0ad007ed90"
      define_method(:install) do
        bin.install "flashpoint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.1.0/flashpoint_0.1.0_linux_arm64.tar.gz"
      sha256 "9de7904443e411a5c1fee3f264f5369c9ae1bd66e061e3b99c166827a67f1d1c"
      define_method(:install) do
        bin.install "flashpoint"
      end
    end
  end

  test do
    assert_match "flashpoint", shell_output("#{bin}/flashpoint --version")
  end
end
