# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flashpoint < Formula
  desc "Hot reload for Go HTTP servers with a Vite/React front end, without dropped requests"
  homepage "https://github.com/danielloader/flashpoint"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.3.0/flashpoint_0.3.0_darwin_x86_64.tar.gz"
      sha256 "0b36c5aba8bb58d9d41422c0446047976394647526891be0f1c3e2720e7ac3a5"

      define_method(:install) do
        bin.install "flashpoint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.3.0/flashpoint_0.3.0_darwin_arm64.tar.gz"
      sha256 "03aba2738286d2a79f4820ac9b4b393fcb61fa7691f09012deee5d382cdffa65"

      define_method(:install) do
        bin.install "flashpoint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.3.0/flashpoint_0.3.0_linux_x86_64.tar.gz"
      sha256 "f761337b18b3d9ec556eee625de8bde425830d6da1e809e421a9899f12f52bb7"
      define_method(:install) do
        bin.install "flashpoint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.3.0/flashpoint_0.3.0_linux_arm64.tar.gz"
      sha256 "df47851aeae290bf8a3f6673efa283b841817b3fa2853fae57fa228f8756dca8"
      define_method(:install) do
        bin.install "flashpoint"
      end
    end
  end

  test do
    assert_match "flashpoint", shell_output("#{bin}/flashpoint --version")
  end
end
