# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flashpoint < Formula
  desc "Hot reload for Go HTTP servers with a Vite/React front end, without dropped requests"
  homepage "https://github.com/danielloader/flashpoint"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.3.1/flashpoint_0.3.1_darwin_x86_64.tar.gz"
      sha256 "5a36a8746a691f620bca902a66c192d04a5e05840885d36e01a969b671b2b66c"

      define_method(:install) do
        bin.install "flashpoint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.3.1/flashpoint_0.3.1_darwin_arm64.tar.gz"
      sha256 "b6037e4a7a8a662ad151b513a6b13d1015b698704a9e6f66bb834719f95a0333"

      define_method(:install) do
        bin.install "flashpoint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.3.1/flashpoint_0.3.1_linux_x86_64.tar.gz"
      sha256 "a220d68fdf669a4d6818f31dcdc3f8c1de19b8e3e3616cdc6b68a4193765a67f"
      define_method(:install) do
        bin.install "flashpoint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielloader/flashpoint/releases/download/v0.3.1/flashpoint_0.3.1_linux_arm64.tar.gz"
      sha256 "f99ae8a6329e0b9723a3e9b6d3ee770366990897f0352c82b1880bfa5ed68350"
      define_method(:install) do
        bin.install "flashpoint"
      end
    end
  end

  test do
    assert_match "flashpoint", shell_output("#{bin}/flashpoint --version")
  end
end
