# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waggle < Formula
  desc "Local OpenTelemetry viewer — OTLP/HTTP + OTLP/gRPC ingest into SQLite + Honeycomb-style UI"
  homepage "https://github.com/danielloader/waggle"
  version "0.21.0"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielloader/waggle/releases/download/v0.21.0/waggle_0.21.0_darwin_x86_64.tar.gz"
      sha256 "f0b5adf2794220511d7220c523ba5d84bc3b58427d5753159d02e92eb86e1282"

      define_method(:install) do
        bin.install "waggle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielloader/waggle/releases/download/v0.21.0/waggle_0.21.0_darwin_arm64.tar.gz"
      sha256 "bb646e495e6b128f6b3c922273e09b9db4f585dbbd99466d1627afcea8716ea3"

      define_method(:install) do
        bin.install "waggle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielloader/waggle/releases/download/v0.21.0/waggle_0.21.0_linux_x86_64.tar.gz"
      sha256 "c7511268c1357921ca049217c6a17022d28304255fd67fdd5dce861c406717ca"
      define_method(:install) do
        bin.install "waggle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielloader/waggle/releases/download/v0.21.0/waggle_0.21.0_linux_arm64.tar.gz"
      sha256 "b69b3da0d1610c39a69f9cc2505b0dc90aa8b0fa6dff0b2c1cc0c0a335a5c892"
      define_method(:install) do
        bin.install "waggle"
      end
    end
  end

  test do
    assert_match "waggle", shell_output("#{bin}/waggle --version")
  end
end
