# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waggle < Formula
  desc "Local OpenTelemetry viewer — OTLP/HTTP + OTLP/gRPC ingest into SQLite + Honeycomb-style UI"
  homepage "https://github.com/danielloader/waggle"
  version "0.20.0"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielloader/waggle/releases/download/v0.20.0/waggle_0.20.0_darwin_x86_64.tar.gz"
      sha256 "f51c01e4e9d5dc780bc7f63bd95a1b866ac08cc791ae725067abf9b6cc194ec2"

      define_method(:install) do
        bin.install "waggle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielloader/waggle/releases/download/v0.20.0/waggle_0.20.0_darwin_arm64.tar.gz"
      sha256 "7777ae428b0be0d1dd1082c01079b361f6a78747863901b8c218c40ae9fed449"

      define_method(:install) do
        bin.install "waggle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielloader/waggle/releases/download/v0.20.0/waggle_0.20.0_linux_x86_64.tar.gz"
      sha256 "c0c6e00bd97c123380ec84e3b92a32f5b6c87a9f5ee769176dcd9379f825eff6"
      define_method(:install) do
        bin.install "waggle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielloader/waggle/releases/download/v0.20.0/waggle_0.20.0_linux_arm64.tar.gz"
      sha256 "0c159184cc8005f327b96a304fb3fd72a217bd638b1b60ccad430cdb2009eb5c"
      define_method(:install) do
        bin.install "waggle"
      end
    end
  end

  def caveats
    <<~EOS
      Run waggle in the foreground:
        waggle
      Or run it as a background service (LaunchAgent on macOS):
        brew services start waggle
      Logs (when running as a service):
        #{var}/log/waggle.log
    EOS
  end

  service do
    run [opt_bin/"waggle", "--no-open-browser"]
    keep_alive true
    log_path var/"log/waggle.log"
    error_log_path var/"log/waggle.log"
  end

  test do
    assert_match "waggle", shell_output("#{bin}/waggle --version")
  end
end
